<?php
/************************************************************************/
/* NPDS DUNE : Net Portal Dynamic System .                              */
/* ===========================                                          */
/*                                                                      */
/* This version name NPDS Copyright (c) 2001-2007 by Philippe Brunier   */
/*                                                                      */
/* This program is free software. You can redistribute it and/or modify */
/* it under the terms of the GNU General Public License as published by */
/* the Free Software Foundation; either version 2 of the License.       */
/************************************************************************/
// OBJET : Ce fichier vous permet de personnaliser la page de Login


echo "<p align=\"center\"><a href=\"static.php?op=charte.html&amp;npds=1\" class=\"noir\">Charte d'utilisation du site</a></p>";
?>