<?php
/************************************************************************/
/* NPDS DUNE : Net Portal Dynamic System .                              */
/* ===========================                                          */
/*                                                                      */
/* This version name NPDS Copyright (c) 2001-2007 by Philippe Brunier   */
/*                                                                      */
/* This program is free software. You can redistribute it and/or modify */
/* it under the terms of the GNU General Public License as published by */
/* the Free Software Foundation; either version 2 of the License.       */
/************************************************************************/


   echo "<p align=\"center\">-:&nbsp;<a href=\"static.php?op=charte.html&amp;npds=1&amp;metalang=1\" class=\"noir\">".aff_langue("[french]Charte d'utilisation du site[/french][english]Terms of use[/english]")."</a>&nbsp;:-</p>";
?>