<?php
/************************************************************************/
/* NPDS DUNE : Net Portal Dynamic System .                              */
/* ===========================                                          */
/*                                                                      */
/* NPDS Copyright (c) 2002-2018 by Philippe Brunier                     */
/*                                                                      */
/* This program is free software. You can redistribute it and/or modify */
/* it under the terms of the GNU General Public License as published by */
/* the Free Software Foundation; either version 2 of the License.       */
/************************************************************************/

echo '
<link rel="stylesheet" href="themes/Rev2016/style/rocssti-fr.css">
<link rel="stylesheet" href="themes/Rev2016/cssmenu/styles.css">
<link rel="stylesheet" href="themes/Rev2016/responsivetab/css/easy-responsive-tabs.css" />
<link rel="stylesheet" type="text/css" href="https://fonts.googleapis.com/css?family=Open+Sans:400,700)">
<link rel="stylesheet" href="themes/Rev2016/style/responsiveslides.css"/>';
?>
