<?php
/************************************************************************/
/* DUNE by NPDS                                                         */
/* ===========================                                          */
/*                                                                      */
/* NPDS Copyright (c) 2002-2015 by Philippe Brunier                     */
/*                                                                      */
/* This program is free software. You can redistribute it and/or modify */
/* it under the terms of the GNU General Public License as published by */
/* the Free Software Foundation; either version 2 of the License.       */
/************************************************************************/

echo '
<link rel="stylesheet" href="lib/css/glyphicons.css" />
<link rel="stylesheet" href="lib/css/glyphicons-bootstrap.css" />
<link rel="stylesheet" href="lib/bootstrap-datepicker/dist/css/bootstrap-datepicker.min.css" />
<link rel="stylesheet" href="lib/css/octicons.css" />
<link rel="stylesheet" href="lib/js/highlight-9.0.0/styles/vs.css" />';
echo '
<script type="text/javascript" src="lib/js/jquery-2.1.4.min.js"></script>';
echo '
<script type="text/javascript" src="lib/js/tether.min.js"></script>';
echo '
<script type="text/javascript" src="lib/bootstrap/dist/js/bootstrap.min.js"></script>';
echo '
<script type="text/javascript" src="lib/bootstrap-table/dist/bootstrap-table.js"></script>
<script type="text/javascript" src="lib/bootstrap-table/dist/locale/bootstrap-table-'.language_iso(1,"-",1).'.min.js"></script>
<script type="text/javascript" src="lib/bootstrap-table/dist/extensions/mobile/bootstrap-table-mobile.min.js"></script>
<script type="text/javascript" src="lib/bootstrap-table/dist/extensions/export/bootstrap-table-export.min.js"></script>
<script type="text/javascript" src="lib/tableExport.jquery.plugin-master/tableExport.js"></script>
<script type="text/javascript" src="lib/js/js.cookie.js"></script>
<script type="text/javascript" src="lib/js/jquery-ui.min.js"></script>
<script type="text/javascript" src="lib/js/bootbox.min.js"></script>
<script type="text/javascript" src="lib/bootstrap-datepicker/dist/js/bootstrap-datepicker.min.js"></script>
<script type="text/javascript" src="lib/bootstrap-datepicker/dist/locales/bootstrap-datepicker.'.language_iso(1,"","").'.min.js"></script>
<script type="text/javascript" src="lib/js/highlight-9.0.0/highlight.pack.js"></script>';
?>
