<?php
/************************************************************************/
/* NPDS DUNE : Net Portal Dynamic System .                              */
/* ===========================                                          */
/*                                                                      */
/* This version name NPDS Copyright (c) 2001-2019 by Philippe Brunier   */
/*                                                                      */
/* This program is free software. You can redistribute it and/or modify */
/* it under the terms of the GNU General Public License as published by */
/* the Free Software Foundation; either version 2 of the License.       */
/************************************************************************/

// ATTENTION : Les lignes de ce fichier ne doivent contenir que du JAVASCRIPT et en aucun cas du PHP ou du HTML
// BEWARE    : The lines of this file are to be JAVASCRIPT and never PHP or HTML code
?>