<?php
/************************************************************************/
/* NPDS DUNE : Net Portal Dynamic System .                              */
/* ===========================                                          */
/*                                                                      */
/* This version name NPDS Copyright (c) 2001-2007 by Philippe Brunier   */
/*                                                                      */
/* This program is free software. You can redistribute it and/or modify */
/* it under the terms of the GNU General Public License as published by */
/* the Free Software Foundation; either version 2 of the License.       */
/************************************************************************/



?>
<meta name="viewport" content="width=device-width,initial-scale= 1"/>

<link rel="stylesheet" href="lib/font-awesome-4.3.0/css/font-awesome.min.css" />
<link rel="stylesheet" href="lib/css/glyphicons.css" />
<link rel="stylesheet" href="lib/css/glyphicons-bootstrap.css" />

<link rel="stylesheet" href="themes/0-foundation/style/ajust.css">
<link rel="stylesheet" href="themes/0-foundation/style/foundation.css">
<link rel="stylesheet" href="themes/0-foundation/style/normalize.css">

  <script src="themes/01pure /js/foundation.min.js"></script>
  
  <script src="themes/0-foundation /js/vendor/fastclick.js"></script>
  <script src="themes/0-foundation /js/vendor/jquery.cookie.js"></script>
  <script src="themes/0-foundation /js/vendor/jquery.js"></script>
  <script src="themes/0-foundation /js/vendor/modernizr.js"></script>
  <script src="themes/0-foundation /js/vendor/placeholder.js"></script>




  <script src="http://ajax.googleapis.com/ajax/libs/jquery/1.8.3/jquery.min.js"></script>
  <script src="themes/01pure /js/responsiveslides.min.js"></script>
  <script>
    // You can also use "$(window).load(function() {"
    $(function () {

      // Slideshow 1
      $("#slider1").responsiveSlides({
        maxwidth: 800,
        speed: 800
      });
 });
  </script>