<?php
/************************************************************************/
/* NPDS DUNE : Net Portal Dynamic System .                              */
/* ===========================                                          */
/*                                                                      */
/* This version name NPDS Copyright (c) 2001-2015 by Philippe Brunier   */
/*                                                                      */
/* This program is free software. You can redistribute it and/or modify */
/* it under the terms of the GNU General Public License as published by */
/* the Free Software Foundation; either version 2 of the License.       */
/************************************************************************/

// since NPDS Rev 16 this ressources are required dont remove //
echo '
<link rel="stylesheet" href="lib/font-awesome-4.5.0/css/font-awesome.min.css" />
<link rel="stylesheet" href="lib/font-awesome-4.5.0/fa-snapchat.css">'; // web font
echo '
<link id="bsth" rel="stylesheet" href="lib/bootstrap-4.0.0-alpha.2/dist/css/bootstrap.min.css" />'; // framework
echo '
<link id="bsthxtra" rel="stylesheet" href="lib/bootstrap-4.0.0-alpha.2/dist/css/extra.css" />'; // develop
echo '
<link rel="stylesheet" href="lib/formvalidation-dist-v0.7.0/dist/css/formValidation.min.css" />'; // form control
echo '
<link rel="stylesheet" href="lib/jquery-ui.css">';
echo '
<link rel="stylesheet" href="lib/bootstrap-table/dist/bootstrap-table.css" />'; // table
?>