<?php
/************************************************************************/
/* NPDS DUNE : Net Portal Dynamic System .                              */
/* ===========================                                          */
/*                                                                      */
/* This version name NPDS Copyright (c) 2001-2024 by Philippe Brunier   */
/*                                                                      */
/* This program is free software. You can redistribute it and/or modify */
/* it under the terms of the GNU General Public License as published by */
/* the Free Software Foundation; either version 3 of the License.       */
/************************************************************************/
// OBJET : Ce fichier vous permet de personnaliser la page de Login et le plan du site
   echo '
   <p class="text-center my-3">
      <a class="btn btn-outline-primary btn-sm" href="static.php?op=charte.html&amp;npds=1&amp;metalang=1">'.aff_langue("[french]Charte d'utilisation du site[/french][english]Terms of use[/english]").'</a>
   </p>';
?>