<?php
/************************************************************************/
/* NPDS DUNE : Net Portal Dynamic System .                              */
/* ===========================                                          */
/*                                                                      */
/* This version name NPDS Copyright (c) 2001-2019 by Philippe Brunier   */
/*                                                                      */
/* This program is free software. You can redistribute it and/or modify */
/* it under the terms of the GNU General Public License as published by */
/* the Free Software Foundation; either version 2 of the License.       */
/************************************************************************/
// $time_start = getmicrotime(); //utilise la fonction du mainfile pour PHP < 5
// define('TIMESTART',getmicrotime()); // constante à la place de variable < 5
// $time_start = microtime(true); // n'utilise pas la fonction du mainfile mais native PHP => 5

define('TIMESTART',microtime(true)); // avec constante pour PHP => 5

?>